### PR TITLE
Update tag.py

### PR DESCRIPTION
**Pull request by ch-yx**
I feel not good with the "import nbtlib"......
I think "Relative path" is better...
it is too hardcode now😖

### CODE REVIEW

**Comment by ch-yx** [comment]
and fixed a typo.

**Comment by vberlier** [comment]
Hmm I agree... it's a bit inconsistent, but local imports are actually a [PEP 8](https://www.python.org/dev/peps/pep-0008/#imports) violation. The most common way to deal with circular imports is to import the module and lazily access the attribute you need.

**Comment by vberlier** [comment]
I'm fixing that typo though, thanks for pointing it out!

**Comment by ch-yx** [comment]
emmmm 


i noticed that all "path"s in the file is in "isinstance(item,path)". 


Why not just replace all the paths in the file with named tuple? 
as path is a subclass of named tuple.



---

or we can use hasattr instead?
hasattr(item,"this is a nbt path")🤔

**Comment by vberlier** [comment]
Actually one way to do it is to invert the conditional branches and check for `isinstance(key, str)` instead. Just did that in 77a49e0. For list tags I'm using `isinstance(index, (int, slice))`.

**Comment by ch-yx** [comment]
> 
> 
> Actually one way to do it is to invert the conditional branches and check for `isinstance(key, str)` instead. Just did that in [77a49e0](https://github.com/vberlier/nbtlib/commit/77a49e0252b52dac016010b37554b303db85efc7). For list tags I'm using `isinstance(index, (int, slice))`.


Actually, I dont think that is the best solution.
I suggest that give path object a special attribute, then decide if it is a path by using
`hasattr(item,"this_is_a_nbt_path")`.

As there is a minor fault in the current https://github.com/vberlier/nbtlib/commit/77a49e0252b52dac016010b37554b303db85efc7 :

```
>>> [1,2,3,4,5][type("",(),{"__index__":lambda x:2})()]
3
```
index is not forced to be a int.

if you could reverse to https://github.com/vberlier/nbtlib/pull/46/commits/87bae21f81c783b0e6266316336138ed4ac828b8 ,(Then replace "isinstance"  with "hasattr")I will be really appreciated.


@vberlier

**Pull request closed without merging**
